apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: reverse-words-build-pipeline-run-
spec:
  serviceAccountName: reversewords-pipeline
  pipelineRef:
    name: reverse-words-build-pipeline
  params:
    - name: imageTag
      value: "testing"
  resources:
    - name: app-git
      resourceRef:
        name: reverse-words-git
    - name: app-image
      resourceRef:
        name: reverse-words-image
