apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: reverseword-build-triggertemplate
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: reversewords-git-$(uid)
      spec:
        type: git
        params:
        - name: revision
          value: $(body.head_commit.id)
        - name: url
          value: $(body.repository.clone_url)
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: reversewords-build-pipeline-run-$(uid)
      spec:
        pipelineRef:
          name: reverse-words-build-pipeline
        serviceAccountNames:
          - taskName: build-and-push
            serviceAccountName: reversewords-pipeline
        params:
          - name: imageTag
            value: $(params.gitrevision)
        resources:
          - name: app-git
            resourceRef:
              name: reversewords-git-$(uid)
          - name: app-image
            resourceRef:
              name: reverse-words-image
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-triggerbinding
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: $(body.repository.url)

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reverse-words-role
rules:
# Permissions for every EventListener deployment to function
 - apiGroups: ["triggers.tekton.dev"]
   resources: ["eventlisteners", "triggerbindings", "triggertemplates"]
   verbs: ["get"]
 - apiGroups: [""]
   resources: ["configmaps"]
   verbs: ["get", "list", "watch"]
# Permissions to create resources in associated TriggerTemplates
 - apiGroups: ["tekton.dev"]
   resources: ["pipelineruns"]
   verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reverse-words-rolebinding
subjects:
- kind: ServiceAccount
  name: reversewords-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: reverse-words-role

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: webhook
spec:
  serviceAccountName: pipeline
  triggers:
    - name: pullrequest-reversewords
      bindings:
      - ref: github-triggerbinding
      template:
        name: reverseword-build-triggertemplate
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: webhook
  name: el-webhook
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-webhook
    weight: 100
